name: Run Code Review with ChatGPT

on:
  push:
    branches:
      - master

jobs:
  review-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ChatGPT Reviewer
        uses: adityamindcrew/UltraFair@master 